version: "3"

services: 
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200/tcp
    environment: 
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    networks: 
      - logging-network

  logstash:
    container_name: logstash
    image: logstash:7.3.2
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logfiles/:/usr/share/logstash/logfiles/
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    networks:
      - logging-network

  kibana:
    container_name: kibana
    image: kibana:7.3.2
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - logging-network

networks: 
  logging-network:
    driver: bridge
